version: "3.9"
services:
  api:
    restart: "unless-stopped"
    build:
      context: .
      args:
        BASE_URL: /ruderobot
    networks:
      net:
        ipv4_address: 172.102.0.1
    environment:
      OPENAI_API_KEY: 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
      MONGO_CONNECTION_STRING: mongodb://root:rootPassword@172.18.0.2:27017
    ports:
      - "8112:80"
    depends_on:
      - db

  db:
    restart: "unless-stopped"
    image: mongo
    networks:
      net:
        ipv4_address: 172.102.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
    ports:
      - "27017:27017"
    volumes:
      - "db-volume:/data/db"


volumes:
  db-volume: {}


networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.102.0.0/16
          gateway: 172.102.0.254